import QuantyraNullCone

#check QuantyraNullCone.finite_realizer_rank_rigidity
#check QuantyraNullCone.finite_realizer_rank_rigidity_specified
#check QuantyraNullCone.finite_realizer_coordinate_rigidity
#check QuantyraNullCone.finite_realizer_cumulative_error
#check QuantyraNullCone.sampledOrder_measurable
#check QuantyraNullCone.InDensityClass.densityMeasure_univ
#check QuantyraNullCone.InDensityClass.orderLaw_isProbabilityMeasure
#check QuantyraNullCone.InDensityClass.uMarginal_mass
#check QuantyraNullCone.InDensityClass.vMarginal_mass
#check QuantyraNullCone.InDensityClass.populationCDF_thresholdStability
#check QuantyraNullCone.InDensityClass.populationCDF_u_one
#check QuantyraNullCone.InDensityClass.populationCDF_one_v
#check QuantyraNullCone.grid_marginal_accuracy_uniform
#check QuantyraNullCone.boundary_card_le_of_grid_marginals
#check QuantyraNullCone.grid_vertices_empiricalCDF
#check QuantyraNullCone.finite_realizer_cumulative_error_of_grid_vertices
#print axioms QuantyraNullCone.finite_realizer_rank_rigidity
#print axioms QuantyraNullCone.finite_realizer_rank_rigidity_specified
#print axioms QuantyraNullCone.finite_realizer_coordinate_rigidity
#print axioms QuantyraNullCone.finite_realizer_cumulative_error
#print axioms QuantyraNullCone.sampledOrder_measurable
#print axioms QuantyraNullCone.InDensityClass.densityMeasure_univ
#print axioms QuantyraNullCone.InDensityClass.orderLaw_isProbabilityMeasure
#print axioms QuantyraNullCone.InDensityClass.uMarginal_mass
#print axioms QuantyraNullCone.InDensityClass.vMarginal_mass
#print axioms QuantyraNullCone.InDensityClass.populationCDF_thresholdStability
#print axioms QuantyraNullCone.InDensityClass.populationCDF_u_one
#print axioms QuantyraNullCone.InDensityClass.populationCDF_one_v
#print axioms QuantyraNullCone.grid_marginal_accuracy_uniform
#print axioms QuantyraNullCone.boundary_card_le_of_grid_marginals
#print axioms QuantyraNullCone.grid_vertices_empiricalCDF
#print axioms QuantyraNullCone.finite_realizer_cumulative_error_of_grid_vertices
#check QuantyraNullCone.InDensityClass.sample_ae_mem_diamond
#check QuantyraNullCone.InDensityClass.sample_ae_no_grid_lines
#check QuantyraNullCone.InDensityClass.gridCell_mass_lower
#check QuantyraNullCone.InDensityClass.sample_misses_le_exp
#check QuantyraNullCone.InDensityClass.grid_occupancy_failure
#check QuantyraNullCone.InDensityClass.fst_map_uniform
#check QuantyraNullCone.InDensityClass.snd_map_uniform
#check QuantyraNullCone.InDensityClass.sample_coordinates_injective
#check QuantyraNullCone.InDensityClass.indicator_concentration
#check QuantyraNullCone.InDensityClass.empiricalCDF_concentration
#check QuantyraNullCone.InDensityClass.grid_vertices_failure
#check QuantyraNullCone.InDensityClass.sample_good_probability
#check QuantyraNullCone.InDensityClass.reconstruction_probability_grid
#check QuantyraNullCone.grid_failure_bound
#check QuantyraNullCone.fourth_root_grid_data
#check QuantyraNullCone.InDensityClass.reconstruction_probability
#print axioms QuantyraNullCone.InDensityClass.sample_ae_mem_diamond
#print axioms QuantyraNullCone.InDensityClass.sample_ae_no_grid_lines
#print axioms QuantyraNullCone.InDensityClass.gridCell_mass_lower
#print axioms QuantyraNullCone.InDensityClass.sample_misses_le_exp
#print axioms QuantyraNullCone.InDensityClass.grid_occupancy_failure
#print axioms QuantyraNullCone.InDensityClass.fst_map_uniform
#print axioms QuantyraNullCone.InDensityClass.snd_map_uniform
#print axioms QuantyraNullCone.InDensityClass.sample_coordinates_injective
#print axioms QuantyraNullCone.InDensityClass.indicator_concentration
#print axioms QuantyraNullCone.InDensityClass.empiricalCDF_concentration
#print axioms QuantyraNullCone.InDensityClass.grid_vertices_failure
#print axioms QuantyraNullCone.InDensityClass.sample_good_probability
#print axioms QuantyraNullCone.InDensityClass.reconstruction_probability_grid
#print axioms QuantyraNullCone.grid_failure_bound
#print axioms QuantyraNullCone.fourth_root_grid_data
#print axioms QuantyraNullCone.InDensityClass.reconstruction_probability
#check QuantyraNullCone.InDensityClass.rectangle_mass_cdf
#check QuantyraNullCone.InDensityClass.coefficientDeviation_attained
#check QuantyraNullCone.InDensityClass.coefficient_interpolation
#print axioms QuantyraNullCone.InDensityClass.rectangle_mass_cdf
#print axioms QuantyraNullCone.InDensityClass.coefficientDeviation_attained
#print axioms QuantyraNullCone.InDensityClass.coefficient_interpolation
#check QuantyraNullCone.chronological_realizer_exists
#check QuantyraNullCone.selectedCDF_measurable
#check QuantyraNullCone.InDensityClass.orderCDFGood_probability
#check QuantyraNullCone.finite_probability_event_bound
#check QuantyraNullCone.InDensityClass.orderLawTV_event_bound
#check QuantyraNullCone.InDensityClass.orderCDFGood_intersects
#check QuantyraNullCone.InDensityClass.populationCDF_orbit_of_orderLawTV
#print axioms QuantyraNullCone.chronological_realizer_exists
#print axioms QuantyraNullCone.selectedCDF_measurable
#print axioms QuantyraNullCone.InDensityClass.orderCDFGood_probability
#print axioms QuantyraNullCone.finite_probability_event_bound
#print axioms QuantyraNullCone.InDensityClass.orderLawTV_event_bound
#print axioms QuantyraNullCone.InDensityClass.orderCDFGood_intersects
#print axioms QuantyraNullCone.InDensityClass.populationCDF_orbit_of_orderLawTV
#check QuantyraNullCone.InDensityClass.transpose
#check QuantyraNullCone.diamondVolume_transpose_preserving
#check QuantyraNullCone.densityMeasure_transpose_apply
#check QuantyraNullCone.populationCDF_transpose
#check QuantyraNullCone.coefficientDeviation_transpose_both
#check QuantyraNullCone.InDensityClass.coefficientDeviation_bounds
#check QuantyraNullCone.InDensityClass.conformalDistance_bounds
#check QuantyraNullCone.orderLawTV_le_finiteLawDiscrepancy
#check QuantyraNullCone.InDensityClass.conformalDistance_of_small_TV
#check QuantyraNullCone.InDensityClass.full_inverse
#check QuantyraNullCone.InDensityClass.coefficientDeviation_zero_iff
#check QuantyraNullCone.InDensityClass.conformalDistance_zero_iff
#check QuantyraNullCone.InDensityClass.all_law_identifiability
#print axioms QuantyraNullCone.InDensityClass.transpose
#print axioms QuantyraNullCone.diamondVolume_transpose_preserving
#print axioms QuantyraNullCone.densityMeasure_transpose_apply
#print axioms QuantyraNullCone.populationCDF_transpose
#print axioms QuantyraNullCone.coefficientDeviation_transpose_both
#print axioms QuantyraNullCone.InDensityClass.coefficientDeviation_bounds
#print axioms QuantyraNullCone.InDensityClass.conformalDistance_bounds
#print axioms QuantyraNullCone.orderLawTV_le_finiteLawDiscrepancy
#print axioms QuantyraNullCone.InDensityClass.conformalDistance_of_small_TV
#print axioms QuantyraNullCone.InDensityClass.full_inverse
#print axioms QuantyraNullCone.InDensityClass.coefficientDeviation_zero_iff
#print axioms QuantyraNullCone.InDensityClass.conformalDistance_zero_iff
#print axioms QuantyraNullCone.InDensityClass.all_law_identifiability
#check QuantyraNullCone.sampledOrder_strict_partial_order
#check QuantyraNullCone.InDensityClass.sample_relabel_preserving
#check QuantyraNullCone.InDensityClass.orderLaw_exchangeable
#check QuantyraNullCone.InDensityClass.orderLaw_singleton_relabel
#check QuantyraNullCone.abs_sum_of_constant
#check QuantyraNullCone.finite_map_L1_of_fiber_constant
#check QuantyraNullCone.forgetOrderLabels_eq_iff
#check QuantyraNullCone.InDensityClass.unlabeledOrderLaw_isProbabilityMeasure
#check QuantyraNullCone.InDensityClass.orderLaw_fiber_constant
#check QuantyraNullCone.InDensityClass.unlabeledOrderLawTV_eq
#check QuantyraNullCone.InDensityClass.unlabeledFiniteLawDiscrepancy_eq
#check QuantyraNullCone.InDensityClass.full_inverse_unlabeled
#check QuantyraNullCone.InDensityClass.all_unlabeled_law_identifiability
#print axioms QuantyraNullCone.sampledOrder_strict_partial_order
#print axioms QuantyraNullCone.InDensityClass.sample_relabel_preserving
#print axioms QuantyraNullCone.InDensityClass.orderLaw_exchangeable
#print axioms QuantyraNullCone.InDensityClass.orderLaw_singleton_relabel
#print axioms QuantyraNullCone.abs_sum_of_constant
#print axioms QuantyraNullCone.finite_map_L1_of_fiber_constant
#print axioms QuantyraNullCone.forgetOrderLabels_eq_iff
#print axioms QuantyraNullCone.InDensityClass.unlabeledOrderLaw_isProbabilityMeasure
#print axioms QuantyraNullCone.InDensityClass.orderLaw_fiber_constant
#print axioms QuantyraNullCone.InDensityClass.unlabeledOrderLawTV_eq
#print axioms QuantyraNullCone.InDensityClass.unlabeledFiniteLawDiscrepancy_eq
#print axioms QuantyraNullCone.InDensityClass.full_inverse_unlabeled
#print axioms QuantyraNullCone.InDensityClass.all_unlabeled_law_identifiability

#check QuantyraNullCone.log_large_bounds
#check QuantyraNullCone.logarithmic_grid_data
#check QuantyraNullCone.logarithmic_grid_failure
#check QuantyraNullCone.logarithmic_grid_reciprocal
#check QuantyraNullCone.InDensityClass.logarithmic_reconstruction_probability
#check QuantyraNullCone.InDensityClass.logarithmic_orderCDFGood_probability
#check QuantyraNullCone.InDensityClass.logarithmic_populationCDF_orbit_of_orderLawTV
#check QuantyraNullCone.logarithmic_small_sample_lower
#check QuantyraNullCone.InDensityClass.full_inverse_logarithmic
#check QuantyraNullCone.InDensityClass.full_inverse_logarithmic_unlabeled
#print axioms QuantyraNullCone.log_large_bounds
#print axioms QuantyraNullCone.logarithmic_grid_data
#print axioms QuantyraNullCone.logarithmic_grid_failure
#print axioms QuantyraNullCone.logarithmic_grid_reciprocal
#print axioms QuantyraNullCone.InDensityClass.logarithmic_reconstruction_probability
#print axioms QuantyraNullCone.InDensityClass.logarithmic_orderCDFGood_probability
#print axioms QuantyraNullCone.InDensityClass.logarithmic_populationCDF_orbit_of_orderLawTV
#print axioms QuantyraNullCone.logarithmic_small_sample_lower
#print axioms QuantyraNullCone.InDensityClass.full_inverse_logarithmic
#print axioms QuantyraNullCone.InDensityClass.full_inverse_logarithmic_unlabeled

example {rho sigma : QuantyraNullCone.DiamondPoint → ℝ}
    (hR : QuantyraNullCone.InDensityClass rho) (hS : QuantyraNullCone.InDensityClass sigma)
    {N : ℕ} (hN : 2 ≤ N) :
    QuantyraNullCone.conformalDistance rho sigma ≤
      130 * ((Real.log (N : ℝ) / N) ^ (1 / 6 : ℝ) +
        QuantyraNullCone.unlabeledFiniteLawDiscrepancy rho sigma N) :=
  hR.full_inverse_logarithmic_unlabeled hS hN

#check QuantyraNullCone.sqrt_coefficient_lipschitz
#check QuantyraNullCone.FutureCurve.integral_derivU
#check QuantyraNullCone.FutureCurve.integral_derivV
#check QuantyraNullCone.FutureCurve.integral_weight_cauchy_schwarz
#check QuantyraNullCone.FutureCurve.integrable_length
#check QuantyraNullCone.FutureCurve.length_difference
#check QuantyraNullCone.timeSeparation_empty
#check QuantyraNullCone.InDensityClass.timeSeparation_difference
#check QuantyraNullCone.InDensityClass.timeSeparation_transpose
#check QuantyraNullCone.InDensityClass.proper_time_conformalDistance
#check QuantyraNullCone.InDensityClass.proper_time_inverse_unlabeled
#check QuantyraNullCone.InDensityClass.proper_time_logarithmic_unlabeled
#print axioms QuantyraNullCone.sqrt_coefficient_lipschitz
#print axioms QuantyraNullCone.FutureCurve.integral_derivU
#print axioms QuantyraNullCone.FutureCurve.integral_derivV
#print axioms QuantyraNullCone.FutureCurve.integral_weight_cauchy_schwarz
#print axioms QuantyraNullCone.FutureCurve.integrable_length
#print axioms QuantyraNullCone.FutureCurve.length_difference
#print axioms QuantyraNullCone.timeSeparation_empty
#print axioms QuantyraNullCone.InDensityClass.timeSeparation_difference
#print axioms QuantyraNullCone.InDensityClass.timeSeparation_transpose
#print axioms QuantyraNullCone.InDensityClass.proper_time_conformalDistance
#print axioms QuantyraNullCone.InDensityClass.proper_time_inverse_unlabeled
#print axioms QuantyraNullCone.InDensityClass.proper_time_logarithmic_unlabeled

example {rho sigma : QuantyraNullCone.DiamondPoint → ℝ}
    (hR : QuantyraNullCone.InDensityClass rho) (hS : QuantyraNullCone.InDensityClass sigma)
    {N : ℕ} (hN : 2 ≤ N) :
    ∃ swap : Bool, ∀ p q : QuantyraNullCone.DiamondPoint,
      |QuantyraNullCone.timeSeparation rho p q - QuantyraNullCone.timeSeparation sigma
        (QuantyraNullCone.alignedPoint swap p) (QuantyraNullCone.alignedPoint swap q)| ≤
      130 * ((Real.log (N : ℝ) / N) ^ (1 / 6 : ℝ) +
        QuantyraNullCone.unlabeledFiniteLawDiscrepancy rho sigma N) :=
  hR.proper_time_logarithmic_unlabeled hS hN
