"""Audit proof source and actual Lean dependency reports; exit nonzero on failure."""
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
ALLOWED = {"propext", "Classical.choice", "Quot.sound"}
sources = [ROOT / "QuantyraNullCone.lean", *sorted((ROOT / "QuantyraNullCone").glob("*.lean")), ROOT / "checks/Audit.lean"]
for path in sources:
    source = path.read_text(encoding="utf-8")
    if re.search(r"\b(?:sorry|admit)\b|^\s*axiom\s", source, re.MULTILINE):
        sys.exit(f"Forbidden proof token or axiom declaration: {path.relative_to(ROOT)}")

result = subprocess.run(["lake", "env", "lean", "checks/Audit.lean"], cwd=ROOT,
                        text=True, encoding="utf-8", capture_output=True)
print(result.stdout, end="")
if result.stderr:
    print(result.stderr, file=sys.stderr, end="")
if result.returncode:
    sys.exit(result.returncode)
reports = re.findall(r"depends on axioms:\s*\[([^\]]*)\]", result.stdout)
if not reports:
    sys.exit("No Lean dependency reports found")
for report in reports:
    names = {name.strip() for name in report.split(",") if name.strip()}
    if not names <= ALLOWED:
        sys.exit(f"Unexpected theorem dependencies: {sorted(names - ALLOWED)}")
for name in ('join_integrable_left3',
             'join_integrable_right3',
             'join_integrable3',
             'join_integral_left3',
             'join_integral_right3',
             'join_integral3',
             'join_primitive_left3',
             'join_primitive_right3',
             'joined_coord_AC3',
             'joined_coord_left3',
             'joined_coord_right3',
             'joined_coord_deriv3',
             'ae_left_half3',
             'ae_right_half3',
             'joined_velocity3',
             'joined_future3',
             'FutureCurve3.concat_point_left',
             'FutureCurve3.concat_point_right',
             'FutureCurve3.concat_velocity',
             'flat_proper_speed_smul3',
             'FutureCurve3.concat_weighted_integrand',
             'curve_integral_eq_interval3',
             'FutureCurve3.concat_weightedLength',
             'FutureCurve3.weightedLength_nonneg',
             'weighted_time_reverse_triangle3',
             'InDensityClass3.time_reverse_triangle3',
             'flat_proper_speed_nonneg3',
             'flat_proper_speed_sq3',
             'flat_proper_speed_le_time3',
             'proper_speed_lift_norm3',
             'FutureCurve3.integrable_deriv',
             'FutureCurve3.integral_deriv',
             'FutureCurve3.time_deriv_nonneg',
             'FutureCurve3.endpoint_time_nonneg',
             'FutureCurve3.integrable_flatSpeed',
             'FutureCurve3.integrable_speedLift',
             'FutureCurve3.integral_speedLift',
             'FutureCurve3.integral_speedLift_norm',
             'FutureCurve3.flatLength_nonneg',
             'FutureCurve3.flatLength_sq_bound',
             'FutureCurve3.endpoint_causal',
             'FutureCurve3.flatLength_le_endpoint',
             'FutureCurve3.flatLength_le_two',
             'spatial_radius_smul3',
             'straight_point_causal3',
             'straight_coord_deriv3',
             'straight_curve_velocity3',
             'straight_curve_flatLength3',
             'future_curve_nonempty_iff_causal3',
             'flat_proper_speed_pos_iff3',
             'flat_lengths_bddAbove3',
             'flat_time_separation_nonneg3',
             'flat_time_separation_eq3',
             'flat_time_separation_of_not_causal3',
             'flat_time_separation_pos_iff3',
             'FutureCurve3.continuousOn_point',
             'FutureCurve3.integrable_weightedSpeed',
             'FutureCurve3.weightedLength_bounds',
             'weighted_lengths_bddAbove3',
             'weighted_time_separation_nonneg3',
             'FutureCurve3.weightedLength_le_timeSeparation',
             'weighted_time_separation_of_not_causal3',
             'weighted_time_separation_bounds3',
             'weighted_time_separation_pos_iff3',
             'weighted_time_separation_zero_iff3',
             'weighted_time_profile_eq_iff3',
             'InDensityClass3.timeWeight',
             'InDensityClass3.time_separation_pos_iff3',
             'InDensityClass3.time_profile_eq_iff3',
             'density_time_weight_sq3',
             'density_metric_proper_speed3',
             'FutureCurve3.weightedLength_eq_metric',
             'FutureCurve3.weightedLength_difference',
             'weighted_time_separation_le_add3',
             'weighted_time_separation_difference3',
             'lorentz_waist_subset_closed3',
             'isClosed_lorentzWaist3',
             'isCompact_lorentzWaist3',
             'time_shift_time3',
             'time_shift_radius3',
             'time_shift_sub_radius3',
             'time_shift_radius_sub3',
             'spatial_radius_sub_symm3',
             'spatial_radius_self_sub3',
             'causal3_refl',
             'causal3_transitive',
             'chronological3_trans_causal3',
             'causal3_trans_chronological3',
             'causal3_antisymmetric',
             'bottom_sub_radius3',
             'top_sub_radius3',
             'closed_lorentz_diamond_iff_tips3',
             'lorentz_diamond_iff_tips3',
             'causal_diamond_subset_closed3',
             'causal_diamond_subset_open3',
             'isClosed_causalDiamond3',
             'isCompact_causalDiamond3',
             'open_lorentz_causal_diamond3',
             'past_time_shift_interior3',
             'future_time_shift_interior3',
             'past_chronological_margin3',
             'future_chronological_margin3',
             'lorentz_waist_no_closed_neighbors3',
             'interior_past_iff3',
             'interior_future_iff3',
             'lorentz_interior_iff_neighbors3',
             'lorentz_waist_iff_no_neighbors3',
             'causal3_of_past_inclusion',
             'causal3_of_future_inclusion',
             'chronological_profile_eq_iff3',
             'relabelSample3_apply',
             'sampledOrder3_relabel',
             'sample_relabel_preserving3',
             'orderLaw3_exchangeable',
             'orderLaw3_singleton_relabel',
             'orderLaw3_fiber_constant',
             'orderLaw3_finite',
             'unlabeledOrderLawTV3_eq',
             'finite_measure_eq_of_L1_zero',
             'unlabeledOrderLaw3_eq_iff',
             'InDensityClass3.unlabeledOrderLawTV_eq',
             'InDensityClass3.unlabeledOrderLaw_eq_iff',
             'lower_flat_sample',
             'lower_likelihood_nonneg',
             'lower_likelihood_integrable',
             'lower_sample_withDensity',
             'lower_likelihood_integral',
             'lower_alternative_square_integrable',
             'lower_likelihood_square_integrable',
             'normalized_square_integral',
             'lower_product_divergence_identity',
             'lower_product_divergence_bound',
             'finite_observation_L1_bound',
             'integral_abs_le_sqrt_second',
             'lower_sample_real_apply',
             'lower_order_TV_bound',
             'fourth_root_randomized_lower_bound',
             'fourth_root_lower_exists',
             'fourth_root_minimax_obstruction',
             'odd_gaussian_smooth',
             'odd_gaussian_odd',
             'odd_gaussian_abs_le',
             'odd_gaussian_hasDerivAt',
             'odd_gaussian_deriv_bound',
             'odd_gaussian_lipschitz',
             'lower_profile_smooth',
             'lower_profile_abs_le',
             'lower_profile_lipschitz',
             'lower_profile_primitive',
             'lower_profile_integral_zero',
             'lower_alternative_smooth',
             'lower_alternative_deviation',
             'lower_alternative_bounds',
             'lower_alternative_coordinate_lipschitz',
             'lower_alternative_euclidean_lipschitz',
             'lower_alternative_transpose',
             'lower_alternative_marginal',
             'lower_flat_in_class',
             'lower_alternative_in_class',
             'odd_gaussian_square',
             'odd_gaussian_square_sharp',
             'odd_gaussian_product_sharp',
             'lower_alternative_deviation_sharp',
             'lower_witness_mem',
             'odd_gaussian_witness_square',
             'lower_witness_value',
             'lower_coefficient_separation',
             'lower_quotient_separation',
             'lower_separation_strict',
             'lower_success_disjoint',
             'gaussian_second_integrable',
             'odd_gaussian_square_integrable',
             'odd_gaussian_second_moment',
             'odd_gaussian_second_moment_sq',
             'lower_profile_square_integrable',
             'lower_profile_total_second_moment',
             'lower_profile_truncated_second_moment',
             'lower_single_point_divergence_identity',
             'lower_single_point_divergence_bound',
             'finite_probability_weight_bound',
             'finite_seed_event_decomposition',
             'finite_seed_event_bound',
             'finite_seed_two_point_lower_bound',
             'lower_order_randomized_testing',
             'lower_bandwidth_bounds',
             'lower_bandwidth_budget',
             'lower_bandwidth_large',
             'lower_TV_budget_strict',
             'lower_probability_strict',
             'inner_clamp_bounds',
             'inner_clamp_displacement',
             'inner_clamp_point_mem',
             'InDensityClass.inner_clamp_error',
             'inner_cell_index_lt',
             'inner_cell_location',
             'inner_cell_index_location',
             'inner_histogram_measurable',
             'InDensityClass.inner_histogram_error',
             'Realizer.degreeHistogram_measurable',
             'Realizer.degreeHistogram_bounds',
             'Realizer.degreeCellValue_swap',
             'Realizer.degreeHistogram_swap',
             'degree_histogram_error',
             'degree_inner_mesh_data',
             'degree_mesh_margins',
             'degree_histogram_constant',
             'InDensityClass.square_mass_upper',
             'InDensityClass.shifted_inner_cell_mass',
             'InDensityClass.degree_histogram_probability',
             'degree_logarithmic_mesh_large',
             'InDensityClass.logarithmic_degree_histogram_probability',
             'degree_rate_fourth_power',
             'degree_large_mesh_rate',
             'degree_small_mesh_flat_radius',
             'degree_flat_radius',
             'degree_active_radius',
             'predecessors_reindex_card',
             'rank_reindex',
             'degree_retained_reindex',
             'Realizer.rankPoint_reindex',
             'Realizer.aligned_reindex',
             'Realizer.degreeCellValue_reindex',
             'Realizer.degreeHistogram_reindex',
             'code_degree_reconstructed_sample',
             'code_realizer_relabel',
             'CodeDegreeReconstructed.relabel',
             'selectedDegreeDensity_query_measurable',
             'selectedDegreeDensity_measurable',
             'selectedDegreeDensity_function_measurable',
             'selectedDegreeDensity_bounds',
             'densityEstimateGood_measurable',
             'DensityEstimateGood.mono',
             'degree_reconstruction_quotient',
             'reconstructed_selected_degree',
             'InDensityClass.fourth_root_density_estimation',
             'fourth_root_order_only_estimator',
             'density_estimate_common_orbit',
             'InDensityClass.degree_estimate_intersects',
             'InDensityClass.degree_distance_small_TV',
             'InDensityClass.fourth_root_actual_law_inverse',
             'InDensityClass.sample_good_and_small_mass_probability',
             'degree_event_failure_budget',
             'InDensityClass.degree_event_probability',
             'chronological_predecessor_count',
             'chronological_predecessor_fraction',
             'chronological_successor_count',
             'chronological_successor_fraction',
             'degree_retained_interior',
             'degree_retained_coordinate_rigidity',
             'InDensityClass.densityMeasure_ceiling',
             'InDensityClass.rectangle_mass_bounds',
             'InDensityClass.populationCDF_lower',
             'InDensityClass.northeastCDF_lower',
             'deep_point_degree_retained',
             'eroded_rectangle_recovered',
             'recovered_rectangle_expanded',
             'retained_rectangle_count_sandwich',
             'Realizer.rankPoint_swap',
             'degree_filtered_cell_counts',
             'exp_remainder_le_square',
             'centered_indicator_exp_integrable',
             'indicator_mgf',
             'centered_indicator_mgf_le',
             'iid_indicator_chernoff',
             'InDensityClass.small_mass_count_concentration',
             'InDensityClass.small_mass_family_failure',
             'diamondVolume_probability',
             'InDensityClass.mass_gap_ceiling',
             'diamond_square_cell_real',
             'InDensityClass.shifted_square_mass_gaps',
             'InDensityClass.shifted_cell_mean_error',
             'density_clip_error',
             'InDensityClass.shifted_cell_point_error',
             'chronological3_transitive',
             'chronological_iff_square3',
             'lorentz_flow_separation3',
             'continuousOn_flow_time_parameter3',
             'lorentz_flow_chronological_forward3',
             'lorentz_flow_chronological_iff3',
             'hasFDerivAt_flow_denominator3',
             'hasFDerivAt_flow_numerator3',
             'hasFDerivAt_lorentz_flow3',
             'spatial_radius_sq3',
             'closed_lorentz_diamond_bounds3',
             'chronological3_irreflexive',
             'continuous_spatial_radius3',
             'sampledOrder3_measurable',
             'flat_diamond_measure_mass3',
             'flat_density_class3',
             'sampledOrder3_flow_eq',
             'lorentz_flow_zero3',
             'spatial_radius_flow3',
             'flow_denominator_null_factors3',
             'closed_lorentz_null_bounds3',
             'flow_denominator_lower3',
             'flow_denominator_pos3',
             'flow_factor_pos3',
             'flow_denominator_upper3',
             'gauge_density_bounds3',
             'gauge_density_smooth3',
             'gauge_density_normalized3',
             'gauge_density_class3',
             'gauge_forward_transport3',
             'closed_lorentz_coordinate_square_difference3',
             'gauge_denominator_lipschitz3',
             'reciprocal_cube_lipschitz3',
             'gauge_density_lipschitz3',
             'flow_inverse_denominator_identity3',
             'flow_inverse_denominator3',
             'flow_inverse_factor3',
             'lorentz_flow_inverse3',
             'lorentz_flow_inverse_closed3',
             'gauge_metric_isometry3',
             'higher_dimensional_gauge_counterexample3',
             'lorentz_flow_derivative_matrix3',
             'lorentz_flow_derivative_det3',
             'lorentz_flow_derivative_bilinear3',
             'lorentz_norm_sq3',
             'isCompact_closedLorentzDiamond3',
             'flat_diamond3_ae_mem',
             'InDensityClass3.integrable',
             'InDensityClass3.densityMeasure_univ',
             'InDensityClass3.orderLaw_isProbabilityMeasure',
             'gauge_sample_forward_transport3',
             'gauge_order_laws_equal3',
             'gauge_unlabeled_order_laws_equal3',
             'null_map_bounds3',
             'null_map_strict_bounds3',
             'lorentz_null_plus3',
             'lorentz_null_minus3',
             'lorentz_flow_preserves_closed3',
             'lorentz_flow_preserves_open3',
             'lorentz_flow_image3',
             'lorentz_flow_injectiveOn3',
             'lorentz_flow_smooth3',
             'lorentz_flow_smooth_automorphism3',
             'gauge_density_spatial_invariant3',
             'gauge_anchor_density_gt3',
             'gauge_o2_distance_positive3',
             'lorentz_flow_measurable3',
             'gauge_inverse_transport_volume3',
             'gauge_inverse_transport3',
             'integrable_lorentz_slice_area3',
             'integral_lorentz_slice_area3',
             'lorentz_diamond_volume3',
             'split_lorentz_volume_preserving3',
             'split_lorentz_radius3',
             'split_lorentz_diamond_volume3',
             'lorentz_diamond_volume_slices3',
             'density_cell_flat_value',
             'density_row_sum',
             'density_column_sum',
             'density_prefix_sum',
             'density_objective_sum',
             'check_density_LP_model_sound',
             'DensityCellFeasible.inequality_matrix',
             'InDensityClass.density_LP_feasible',
             'InDensityClass.density_LP_dual_sound',
             'InDensityClass.density_cell_dual_bounds',
             'InDensityClass.density_point_dual_bounds',
             'density_histogram_violation_nonneg',
             'density_histogram_violation_corner',
             'density_histogram_corner_cast',
             'density_histogram_flat_value',
             'density_histogram_box',
             'density_histogram_corners',
             'InDensityClass.density_bands_checked',
             'CDFReport.good_oriented_density',
             'InDensityClass.density_report_checked',
             'InDensityClass.density_report_radius_one',
             'density_report_coverage_measurable',
             'InDensityClass.density_report_coverage',
             'InDensityClass.density_report_fallback_probability',
             'InDensityClass.checked_density_report_coverage',
             'density_fixture_matrix',
             'density_fixture_equalities',
             'density_fixture_right',
             'density_fixture_dimensions',
             'density_fixture_residual',
             'density_fixture_dual_bound',
             'density_fixture_checked',
             'density_fixture_fallback_checked',
             "finite_realizer_rank_rigidity", "finite_realizer_rank_rigidity_specified",
             "finite_realizer_coordinate_rigidity", "finite_realizer_cumulative_error",
             "sampledOrder_measurable", "InDensityClass.densityMeasure_univ",
             "InDensityClass.orderLaw_isProbabilityMeasure", "InDensityClass.uMarginal_mass",
             "InDensityClass.vMarginal_mass", "InDensityClass.populationCDF_thresholdStability",
             "InDensityClass.populationCDF_u_one", "InDensityClass.populationCDF_one_v",
             "grid_marginal_accuracy_uniform", "boundary_card_le_of_grid_marginals",
             "grid_vertices_empiricalCDF", "finite_realizer_cumulative_error_of_grid_vertices",
             "InDensityClass.sample_ae_mem_diamond", "InDensityClass.sample_ae_no_grid_lines",
             "InDensityClass.gridCell_mass_lower", "InDensityClass.sample_misses_le_exp",
             "InDensityClass.grid_occupancy_failure", "InDensityClass.fst_map_uniform",
             "InDensityClass.snd_map_uniform", "InDensityClass.sample_coordinates_injective",
             "InDensityClass.indicator_concentration", "InDensityClass.empiricalCDF_concentration",
             "InDensityClass.grid_vertices_failure", "InDensityClass.sample_good_probability",
             "InDensityClass.reconstruction_probability_grid", "grid_failure_bound",
             "fourth_root_grid_data", "InDensityClass.reconstruction_probability",
             "InDensityClass.rectangle_mass_cdf", "InDensityClass.coefficientDeviation_attained",
             "InDensityClass.coefficient_interpolation", "chronological_realizer_exists",
             "selectedCDF_measurable", "InDensityClass.orderCDFGood_probability",
             "finite_probability_event_bound", "InDensityClass.orderLawTV_event_bound",
             "InDensityClass.orderCDFGood_intersects",
             "InDensityClass.populationCDF_orbit_of_orderLawTV", "InDensityClass.transpose",
             "diamondVolume_transpose_preserving", "densityMeasure_transpose_apply",
             "populationCDF_transpose", "coefficientDeviation_transpose_both",
             "InDensityClass.coefficientDeviation_bounds", "InDensityClass.conformalDistance_bounds",
             "orderLawTV_le_finiteLawDiscrepancy", "InDensityClass.conformalDistance_of_small_TV",
             "InDensityClass.full_inverse", "InDensityClass.coefficientDeviation_zero_iff",
             "InDensityClass.conformalDistance_zero_iff", "InDensityClass.all_law_identifiability",
             "sampledOrder_strict_partial_order",
             "InDensityClass.sample_relabel_preserving",
             "InDensityClass.orderLaw_exchangeable",
             "InDensityClass.orderLaw_singleton_relabel",
             "abs_sum_of_constant",
             "finite_map_L1_of_fiber_constant",
             "forgetOrderLabels_eq_iff",
             "InDensityClass.unlabeledOrderLaw_isProbabilityMeasure",
             "InDensityClass.orderLaw_fiber_constant",
             "InDensityClass.unlabeledOrderLawTV_eq",
             "InDensityClass.unlabeledFiniteLawDiscrepancy_eq",
             "InDensityClass.full_inverse_unlabeled",
             "InDensityClass.all_unlabeled_law_identifiability",
             "log_large_bounds", "logarithmic_grid_data", "logarithmic_grid_failure",
             "logarithmic_grid_reciprocal", "InDensityClass.logarithmic_reconstruction_probability",
             "InDensityClass.logarithmic_orderCDFGood_probability",
             "InDensityClass.logarithmic_populationCDF_orbit_of_orderLawTV",
             "logarithmic_small_sample_lower", "InDensityClass.full_inverse_logarithmic",
             "InDensityClass.full_inverse_logarithmic_unlabeled",
             "sqrt_coefficient_lipschitz",
             "FutureCurve.integral_derivU",
             "FutureCurve.integral_derivV",
             "FutureCurve.integral_weight_cauchy_schwarz",
             "FutureCurve.integrable_length",
             "FutureCurve.length_difference",
             "timeSeparation_empty",
             "InDensityClass.timeSeparation_difference",
             "InDensityClass.timeSeparation_transpose",
             "InDensityClass.proper_time_conformalDistance",
             "InDensityClass.proper_time_inverse_unlabeled",
             "InDensityClass.proper_time_logarithmic_unlabeled",
             "residual_box_bound",
             "finite_lp_weak_duality",
             "rationalDual_checker_sound",
             "Realizer.originalForceStep_sound",
             "Realizer.checkForcingTrace_sound",
             "Realizer.forcing_trace_global_alignment",
             "Realizer.checked_forcing_rank_bounds",
             "negative_exp_upper_512",
             "negative_exp_upper_rational",
             "roundFailureQ_upper",
             "roundFailureQ_le_budget",
             "rounded_split_failure_budget",
             "finite_grid_CDF",
             "normalized_rank_coordinate_error_general",
             "checked_trimmed_CDF",
             "rank_position_eq",
             "checkedPositionRealizer_ranks",
             "dkw_log_ratio_lower",
             "dkw_log_ratio_upper",
             "dkw_stationarity_root",
             "dkw_bernoulli_pinsker",
             "dkw_likelihood_hasDerivAt",
             "dkw_likelihood_derivative_hasDerivAt",
             "dkw_likelihood_stationary_value_lower",
             "dkw_sharp_likelihood_barrier",
             "finite_bin_atom_card",
             "finite_bin_atom_likelihood_identity",
             "finite_bin_terminal_sum",
             "finite_bin_reveal_count",
             "finite_bin_invariant_terminal_sum",
             "finite_bin_likelihood_maximal",
             "finite_bin_deviation_likelihood",
             "finite_bin_upper_DKW",
             "finite_bin_reflect_CDF",
             "finite_bin_two_sided_DKW",
             'uniform_ceil_bin_grid_iff',
             'uniform_quantized_profile_real_mass',
             'uniform_quantized_CDF',
             'uniform_grid_bad_measurable',
             'uniform_grid_DKW',
             'uniform_bad_dyadic_union',
             'uniform_DKW',
             'uniform_DKW_actual_population',
             'InDensityClass.coordinate_sample_uniform',
             'InDensityClass.fst_DKW',
             'InDensityClass.snd_DKW',
             'InDensityClass.split_marginal_failure',
             'InDensityClass.split_joint_grid_failure',
             'InDensityClass.split_confidence_failure',
             'InDensityClass.split_accuracy_probability',
             'split_exponential_upper',
             'InDensityClass.checked_split_calibration',
             'InDensityClass.checked_split_accuracy_probability',
             'InDensityClass.split_rounded_failure',
             'checked_split_rounded_budget',
             'empirical_CDF_bounds',
             'InDensityClass.CDF_radius_one',
             'InDensityClass.split_checked_sample_CDF',
             'CDFReport.checked_rankCDF',
             'CDFReport.radius_one_good',
             'CDFReport.checked_good',
             'cdf_report_coverage_measurable',
             'InDensityClass.cdf_report_coverage',
             'InDensityClass.checked_cdf_report_coverage',
             'permutation_positions_inverse',
             'permutation_rank_decode',
             'CDFReport.corner_CDF',
             'CDFReport.corner_CDF_rational',
             'report_radius_fallback',
             'CDFReport.checked_fallback_good',
             'InDensityClass.cdf_report_fallback_probability',
             'InDensityClass.checked_cdf_report_or_fallback',
             'square_cell_volume',
             'InDensityClass.cell_mean_integral',
             'InDensityClass.cell_mean_bounds',
             'InDensityClass.cell_mean_CDF',
             'cell_chord_distance',
             'cell_chord_integral',
             'cell_majorant_integral',
             'InDensityClass.cell_mean_point_bias',
             'InDensityClass.cell_mean_horizontal',
             'InDensityClass.cell_mean_transpose',
             'InDensityClass.cell_mean_vertical',
             'InDensityClass.grid_cell_bounds',
             'sum_rectangle_differences',
             'InDensityClass.grid_cell_prefix',
             'InDensityClass.grid_cell_row_fin',
             'InDensityClass.grid_cell_column_fin',
             'InDensityClass.grid_cell_horizontal',
             'InDensityClass.grid_cell_vertical',
             'InDensityClass.grid_cell_point_bias',
             'InDensityClass.grid_cell_prefix_restriction',
             'histogram_cell_corner',
             'InDensityClass.histogram_cell_error',
             'InDensityClass.histogram_point_error',
             'InDensityClass.grid_cell_feasible'):
    if not re.search(rf"'QuantyraNullCone\.{re.escape(name)}' "
                     rf"(?:depends on axioms:|does not depend on any axioms)", result.stdout):
        sys.exit(f"Missing final theorem dependency report: {name}")
print("PASS: proof sources and final Lean dependency reports")
